### ISSUE TITLE
Not working when app is cleared from recent task list

### ISSUE THREAD

**Issue by parmarkamlesh** [ravnhq/react-native-midnight#14]
Hi this is great library. its working when Application running in 
background( here it means App is visible to user Or app is in recent task list)

But it is not working when user clear it from recent task list,
Tested in release version of react native app

Thanks.

**Comment by Fortidude** [comment]
@parmarkamlesh  No code can be executed and no listeners can be fired when the app is "dead" / closed.

You should check the date during each app startup

**Comment by parmarkamlesh** [comment]
oke. i have requirement like even app is closed it will show notification mid night when day changed, So can you give me suggestion how to do that?

**Comment by donovanhiland** [comment]
@parmarkamlesh You could schedule a local notification for when you expect the day to change or send a push notification from some server when you think the day changed for the user but you can't have your app listening when it's killed from memory.
